services:
  - type: web
    name: emergency-nlp-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start_render.sh
    plan: starter
    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: PORT
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      # HAPUS FLASK_APP — tidak digunakan oleh Gunicorn
      - key: WEB_CONCURRENCY
        value: 1  # Render Free instance hanya punya 0.1 vCPU, 1 worker lebih stabil

      # Tambahkan secret langsung (opsional), atau isi di dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_PHONE_NUMBER_ID
        sync: false
      - key: FACEBOOK_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false

      # Tambahkan untuk deteksi lingkungan
      - key: RENDER
        value: true