services:
  web:
    name: Lomba
    env: python
    build: .
    start: ./start_render.sh
    # Menggunakan port dinamis dari Render
    ports:
      - http: $PORT
    environment:
      - OPENAI_API_KEY
      - FACEBOOK_ACCESS_TOKEN
      - FACEBOOK_PHONE_NUMBER_ID
      - FACEBOOK_WEBHOOK_VERIFY_TOKEN
      - DATABASE_URL
      - DIRECT_URL
    # Menambahkan koneksi database jika diperlukan
    databases:
      - type: postgresql
        name: emergency-nlp-db
        version: 15
        size: 1GB